### PR TITLE
Milestone two

### PR DESCRIPTION
**Pull request by wajahat414**
used inline bootstrap 4.0
used Grid property of bootstrap
adjusted responsiveness with bootstrap
used infline flex-property of bootstrap
completed requested changes

### CODE REVIEW

**Review by mke2111 — CHANGES_REQUESTED** [review]
# **STATUS: CHANGES REQUIRED 🔴 ⚠️** 

## Hey @wajahat414 & @Chike1990, 👋🏽 
 **Thank you for the good job you got going on. The site runs just fine. Keep it up** 💯 

## REQUIRED CHANGES

- [x] Add a brief description to this PR. You can focus on everything you applied in this milestone.
- [x] The padding (left and right) in mobile screens seems to be a little off as compared to the original site. This is in the More stories and My turn sections. Give this a quick fix. 😄 
Screenshot_2021-03-12_10-40-21

- [x] For the same screen size, your site has a horizontal scroll bar. This implies that the site is not entirely responsive. Look into this and consider fixing it. 🥺 
- [x] Ensure to maintain the same padding (left and right) used throughout the entire site for the mobile screen sizes. Currently, you have three different sizes on this page.

TABLET SCREENS

- [x] The right padding is way greater than its left counterpart. Adjust either side accordingly.
Screenshot_2021-03-12_10-48-09

- [x] The alignment of each opinion in the opinion section is not the same as the original site. Make them similar.
- Your clone
Screenshot_2021-03-12_10-51-49
- Original site
Screenshot_2021-03-12_10-52-51

- [ ] Also change the widths for these scetions accordingly
- Your clone
Screenshot_2021-03-12_10-55-02
- Original site
Screenshot_2021-03-12_10-55-51

- [x] Refactor your CSS code. Some properties used can be added directly to the HTML file and since this milestone is about using Bootstrap, make use of the frameworks' maximum functionality. 

- [x] You need to turn on the actions for linters. Always ensure that github linter checks are active before submitting a CRR.

**Kindly make all the requested changes and submit another CRR. 👍🏽** 

## Cheers!! 🍹 & Happy Coding.


## Ping me on slack for a  🆘  **Roy Mukuye** or mention me [@mke2111](https://github.com/mke2111) in this PR and I'll come through for your inquiries.

**Comment by Chike1990** [comment]
Ok, thank you

**Comment by wajahat414** [comment]
used inline bootstrap 4.0
used Grid property of bootstrap
adjusted responsiveness with bootstrap
used infline flex-property of bootstrap

**Review by cyonii — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️✍️

Hello team, your project is quite wonderful and cool 👏. Good job implementing the changes requested by the previous Reviewer.

## To Improve
There are still a few defects that you need to fix in order for this project to be approved.
- [ ] Some components on the right column has margins that are throwing them off on desktop view. See images
Original Your version
- [x] As previously requested, kindly turn on the stylelint github action, it is a core requirement for this project. In your explanation you said it was behaving strange, I will be glad to help you with that.
- [x] In your **LATEST NEWS** section, you have the even latest news elements nested (_or kind of broken_), please refer to the image below and compare it to the original
Your version


Kindly implement these changes and resubmit for review.
Stay motivated, you came so far already. Happy coding.

### You can find me on slack 👉 [CY Kalu](https://microverse-students.slack.com/team/U01494U96FR) if you need further assistance or clarification. I'm always available and will be glad to help.

**Comment by Chike1990** [comment]
Alright thanks for your reviews

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @wajahat414 & @cyonii**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] there is an alignment issue with the latest news section. please make sure to fix it
issue1

- [ ] the sponsored insights should have an image inside of it. 
issue2
 
---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Review by NtwaliHeritier — APPROVED** [review]
### **STATUS: APPROVED✔✔✔✔✔**

Hello Team,
Great work implementing the required changes.
You can merge

Happy coding💻💻💻

**Comment by Chike1990** [comment]
Thank you, Ntwali

**Pull request merged**
